---
test:
  name: ERC20
  description: This execute ERC20 functions
  clients:
    type: local
    number: 2
  rounds:
  - label: transfer
    txNumber:
    - 200
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    arguments:
      transferMoney: 10
      allowerMoney: 1
      txnPerBatch: 1
    callback: benchmark/erc20/transfer.js
  - label: transfer-approve
    txNumber:
    - 200
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    arguments:
      transferMoney: 10
      allowerMoney: 1
      txnPerBatch: 1
    callback: benchmark/erc20/transfer-approve.js
  - label: transfer-approve-from
    txNumber:
    - 200
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    arguments:
      transferMoney: 10
      allowerMoney: 1
      txnPerBatch: 1
    callback: benchmark/erc20/transfer-approve-transferFrom.js
monitor:
  type:
  - process
  - docker
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  docker:
    name:
    - all
  interval: 1
